#bootline
earlyprintk=sunxi-uart,0x05000000initcall_debug=0console=ttyS0,115200nand_root=/dev/nand0p4mmc_root=/dev/mmcblk0p4init=/initloglevel=3cma=8Mmac=wifi_mac=bt_mac=specialstr=keybox_list=widevine,ec_key,ec_cert1,ec_cert2,ec_cert3,rsa_key,rsa_cert1,rsa_cert2,rsa_cert3setargs_nand=setenv
bootargs
earlyprintk=${earlyprintk}
initcall_debug=${initcall_debug}
console=${console}
loglevel=${loglevel}
root=${nand_root}
init=${init}
partitions=${partitions}
cma=${cma}
snum=${snum}
mac_addr=${mac}
wifi_mac=${wifi_mac}
bt_mac=${bt_mac}
specialstr=${specialstr}
gpt=1setargs_mmc=setenv

bootargs
earlyprintk=${earlyprintk}
initcall_debug=${initcall_debug}
console=${console}
loglevel=${loglevel}
root=${mmc_root}

init=${init}
partitions=${partitions}
cma=${cma}
snum=${snum}
mac_addr=${mac}
wifi_mac=${wifi_mac}
bt_mac=${bt_mac}
specialstr=${specialstr}
gpt=1boot_normal=sunxi_flash
read
45000000
boot;bootm
45000000boot_recovery=sunxi_flash
read
45000000
recovery;bootm
45000000boot_fastboot=fastbootbootdelay=1bootcmd=run
setargs_nand
boot_normal